# Git Repo & Secret
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: state-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/CatalinStratulat/webhook-desired-repo
  ref:
    branch: main
  secretRef:
    name: flux-gitrepo-secret

---
apiVersion: v1
data:
  password: Z2hwX21LTkxCTzhMM2xCdjNEb0Q5SXBCOEtENVRKMkJhSDJlQWF5bg==
  username: Q2F0YWxpblN0cmF0dWxhdA==
kind: Secret
metadata:
  namespace: flux-system
  name: flux-gitrepo-secret
type: Opaque
